language: bash

os:
     - linux

env:
     - PATH=/usr/bin:/bin:./:/usr/local/bin

before_install:
        - uname -a
        - sudo apt-get install -y xz
        - sudo apt-get install -y cabal

script:
 - which shellcheck
 - shellcheck -V
