language: bash

os:   linux
dist: trusty


env:
     - PATH=/usr/bin:/bin:./:/usr/local/bin

before_install:
        - uname -a
        - sudo apt-get install -y xz
        - sudo apt-get install -y cabal

install:
    - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu xenial main universe"
    - sudo apt-get update
    - sudo apt-get install -y cabal
    - sudo apt-get install -y shellcheck

script:
 - which shellcheck
 - shellcheck -V

