matrix:
        allow_failures:
        language: bash
        sudo: false
        include:
                - os: linux
                  dist: bionic
                  env: PATH=/usr/bin:/bin/:./:/usr/local/bin
                  script:
                          - openssl version
                          - shellcheck --version
                          - bash -c 'export SHELLCHECK_OPTS="-S warning"; shopt -s globstar; shellcheck **/*.sh easyrsa3/easyrsa'
                          - sh op_test.sh -vv
                - os: osx
                  osx_image: xcode10.1
                  env: PATH=/usr/bin:/bin/:./:/usr/local/bin
                  script:
                          - sh op_test.sh -vv
